### ISSUE TITLE
Small issues in tutorial

### ISSUE THREAD

**Issue by csku** [luciano-fiandesio/beanborg#11]
Apologies for smooshing multiple issues into a single "Issue", but I wanted to put these down before I forget them.

1. Once installed with `pip`, commands such as bb_import etc should not have the `.py` extension while being run.
2. Tutorial asks user to create `assets.rules` unlike the main `README.md` which correctly specifies the name as 'asset.rules`.
3. It's not super clear that `indexes` should be at the root level of the .yaml file. I thought it was under csv, and I got a NoneType error as a result.

**Comment by luciano-fiandesio** [comment]
Hello, thanks for your comments. Somehow I did not see them when you posted. I'm going to make the corrections to make the tutorial more clear

**Comment by luciano-fiandesio** [comment]
https://github.com/luciano-fiandesio/beanborg/pull/14
