### ISSUE TITLE
Hard dependency on beancount 2.3.3 makes Beanborg incompatible with Fava (which requires >=2.3.5)

### ISSUE THREAD

**Issue by victor-marino** [luciano-fiandesio/beanborg#22]
Hi there!

Was just trying to setup Beancount for the first time, and I wanted to use Fava for its web visualisations and hopefully Beanborg to make importing CSV files easier.

As such, I installed the latest v2 version of Beancount (2.3.6), then the latest version of Fava (which depends on Beancount >=2.3.5). However, when it came to installing Beanborg, it failed because it requires Beancount 2.3.3 specifically, which obviously conflicts with Fava's requirement.

Maybe you're already aware and there's a valid reason for it, but just mentioning it here since I didn't see an open issue for it, just in case this dependency could be easily upgraded.

**Comment by luciano-fiandesio** [comment]
Hi, thanks for reporting, as far as I know there should be no issues in updating beancount to latest, please feel free to make a PR.

**Comment by victor-marino** [comment]
Done :-)

https://github.com/luciano-fiandesio/beanborg/pull/23
